// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDien3xvKsAiO6ifX7gu95c7jY3YJzVRn0',
    appId: '1:112457221838:web:60e2355b27c14fcfdf729f',
    messagingSenderId: '112457221838',
    projectId: 'buffalomilk-aada6',
    authDomain: 'buffalomilk-aada6.firebaseapp.com',
    storageBucket: 'buffalomilk-aada6.firebasestorage.app',
    measurementId: 'G-7YGHMZQ4WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWMszKBT_RJ3NqKNUNiuzNEQmIKB3mLaU',
    appId: '1:112457221838:android:1294fdd341e83a65df729f',
    messagingSenderId: '112457221838',
    projectId: 'buffalomilk-aada6',
    storageBucket: 'buffalomilk-aada6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwWUpuFsGiH-MVaMguetbQnnaJQ-YoPog',
    appId: '1:112457221838:ios:558d84580fab23bcdf729f',
    messagingSenderId: '112457221838',
    projectId: 'buffalomilk-aada6',
    storageBucket: 'buffalomilk-aada6.firebasestorage.app',
    iosBundleId: 'com.example.imageDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwWUpuFsGiH-MVaMguetbQnnaJQ-YoPog',
    appId: '1:112457221838:ios:558d84580fab23bcdf729f',
    messagingSenderId: '112457221838',
    projectId: 'buffalomilk-aada6',
    storageBucket: 'buffalomilk-aada6.firebasestorage.app',
    iosBundleId: 'com.example.imageDetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDien3xvKsAiO6ifX7gu95c7jY3YJzVRn0',
    appId: '1:112457221838:web:d2658e7a7b5fb802df729f',
    messagingSenderId: '112457221838',
    projectId: 'buffalomilk-aada6',
    authDomain: 'buffalomilk-aada6.firebaseapp.com',
    storageBucket: 'buffalomilk-aada6.firebasestorage.app',
    measurementId: 'G-C6NQGN9K2M',
  );
}
